# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/lmg4819/PrivateRepo.git'
source 'git@git.suixinhuan.com:mobile-ios/privateCocoapodsSpec.git'

platform :ios, '9.0'

target 'Example0' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Colours', '~> 5.13.0'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
pod 'Aspects', '~> 1.4.1'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'YTKKeyValueStore', '~> 0.1.2'
#pod 'MJRefresh', '~> 3.1.15.7'
#pod 'MJRefresh', '3.1.12'
pod 'YYModel', '~> 1.0.4'
pod 'YYCache','~> 1.0.4'
pod 'MJRefresh'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'JPFPSStatus', '~> 0.1.1'
pod 'HYBImageCliped', '~> 2.2.4'
pod 'ZYCornerRadius', '~> 1.0.2'
pod 'JSPatch','~> 1.1.3'
pod 'HJCornerRadius', :git => 'https://github.com/panghaijiao/HJCornerRadius.git'
pod 'IQKeyboardManager', '~> 6.1.1'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.7'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'YZDisplayViewController', '~> 1.0.6'
#pod 'MLeaksFinder', '~> 1.0.0'
#pod 'TZImagePickerController', '~> 3.0.5'
pod 'MyLibrary', '0.7.0'
pod 'JSPhotoBrowser','0.2.0'
pod 'MLeaksFinder','~> 1.0.0', :configurations => 'Debug'
pod 'YTKNetwork','2.0.4'
pod 'TTGTagCollectionView','1.9.0'
#pod 'CYPExtension'
end
